language: android

android:
    components:
        - build-tools-23.0.1
        - android-23
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-18

jdk:
    - oraclejdk8

script:
    - ./gradlew ":$MODULE:build" ":$MODULE:test"

after_success:
    - .buildscript/deploy_snapshot.sh

env:
    matrix:
        - MODULE=rxactions
    global:
        - secure: "dSip7OYgrJEjBBY4GdSuP77GjOuJaK6xTyA1SPutAjQ+f06bN6KXh9TCoEr7Nz8H/Vgjv/LxM620HfDCBK361jRmu66phkuyX6f3/3F6vIjUvxuHml4r+FTFirzbItHs6DLeo6XtokcrGuSwl2dS7VLcK0pK+y1+W7eZC90VXBBNsf5ZCsYotcxw8rmf2+GwBszjrEWucozULdLbEyTfxXRlEvsnbIwKDHkWyq027R+k86E6hau4Ch5zMdB/NfRNpvrQPCCAj3jpw9OQ2lBiANjq3+KOO6J2XqTtcVBRKWG52KSIEHPnSg6ei96UK0FQZLpbGTfbkbDhPrsWRuAUO3TnrpEbZ6E/RTSZvtyU77Q70oHjIImfE1IiwNL/mY6IqnB6/YMbTY++75ZKIUezv1ZHwiYMW23OSPsxhrArtBGWNGz+yk53eouPHZpRE7kXct3usJFukUlZHAs6cZqu8n62qYpA6LRH3fJ5B86k8vAn4c3kt9wyGiG9p5gk3ArgJ8TqAHxZXDVN1sdwuRWF7LZCo+AzXKUnpriH3SE560ZVkbjg4ZGRdLJ3BSnlpFYM+roVVkPP2SbGpzqy5728saY012++/6hhDQunTq18ir0hSAgMHb/EVTJ75Sl70JQdEzxd9BcbxFnCGV/VfzPSP3LHLVmkxnaa/CxEM6pxzzk="
        - secure: "U0S+5iePY4z1xuwHBAwTw+aseaN4O3BcPSeNSRnE89Iv6fZbOaXgOWxwbN0XGMiq3Dj86MFb/d2kzXdlfQt3bF2KFjJQ6TVgxqdp8vWMVkTbBjG7/0N/FxZ8rDG9Nod61QtuBtYkWrAitZBy+1NhwkATQNGfVa4a4ct044dUHqjZzq3Iu9IVpc8M4HJShspfU0z7riMR5snepiQLK2LsEf6SWdYJjUyQ1TTwC+hnKqPL0OLXGmE3z1wg9+woIs76f2kj1oSkeLT5PME76kVXpgLsdBdaf74fviQPePkGmenFkuZ0HinAe1ogfbgTCWMNNGwIJL8xe+DmdpGsHVUoFBLZUZHGbEZFkqoqEv8jpNXlLaLMgAg+k3LB2wn08jsODVd8GW1UHHbAlD7/vjSzKJcU08tPmMDMS2iycsdGnYSZx2/9NiMtjWIGx+jFQVfjTbyf44dFPLCMp+eR5X9tDT+halwNrV7K95JNNeNYFh1jOOpHI5HztdlJ+CUW09MbiG6iIBf/crVpimO49h9G64E7LQiAtzaTZwAL40xXHg3ZTY8RZiyzUxT9wcjj45+yYb9RSB6H2/+iKfU+ECVj042lx/spE4y2ReAAC8WP7TsuqbHspRfR9pHAAl9WVXQtGquuziU/lfBsYP0sf7hF4FlLb7Km29RQf2BSnCs2shU="

sudo: false

notifications:
    email: false

cache:
    directories:
        - $HOME/.gradle