language: android

jdk:
    - oraclejdk7

script:
    - ./gradlew ":$MODULE:build" ":$MODULE:test"

after_success:
    - .buildscript/deploy_snapshot.sh

env:
    matrix:
        - MODULE=rxactions

sudo: false

notifications:
    email: false

cache:
    directories:
        - $HOME/.gradle