language: android

android:
    components:
        - build-tools-23.0.1
        - android-23
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-18

jdk:
    - oraclejdk8

script:
    - ./gradlew ":$MODULE:build" ":$MODULE:test"

after_success:
    - .buildscript/deploy_snapshot.sh

env:
    matrix:
        - MODULE=rxactions

sudo: false

notifications:
    email: false

cache:
    directories:
        - $HOME/.gradle